name: Learn Github Action
on:
  push:
    branches:
      - main

jobs:
  npm-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 3.0.0
